### ISSUE TITLE
Bug: Adjust button spacing to perfectly vertically align text and icons

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#794] opened 2018-10-22 19:18 UTC
## Metrics updates introduces some small issues with the vertical alignment.

The icons and the text should be perfectly aligned vertically in both `buttons` and `a` elements. See https://jxnblk.com/formula/

<img width="702" alt="screen shot 2018-10-22 at 2 16 49 pm" src="https://user-images.githubusercontent.com/424119/47313734-512ec400-d605-11e8-865b-12e125e51604.png">

**Comment by ritarora** [comment] 2018-11-21 14:38
@xak This seems duplicate of https://github.com/SAP/fundamental/issues/852 and has been fixed by https://github.com/SAP/fundamental/pull/889

**Closed** 2018-11-21 17:56 UTC
Labels: Bug, Develop, library
