### ISSUE TITLE
Design - Indeterminate State of Checkbox

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#815] opened 2018-10-25 13:41 UTC
Request from Core Systes to include the indeterminate state of a checkbox.
For example, the checkbox with the slash through it in the example below:

![image](https://user-images.githubusercontent.com/24274321/47504376-25485400-d83a-11e8-9efd-4714b8a71f58.png)

**Comment by xak** [comment] 2018-11-02 22:10
Duplicate of #797

**Closed by xak** 2018-11-02 22:10 UTC
